SHOW DATABASES;
USE MYSQL;
DROP TABLE IF EXISTS DEPARTMENT,TEACHER,SUBJECTS,Student,CLASSROOM;
CREATE TABLE DEPARTMENT(
 DEPT_ID VARCHAR(10) PRIMARY KEY,
 DEPT_NAME VARCHAR(60),
 BUDGET INT,
 BUILDING VARCHAR(30)
 );
 
 CREATE TABLE TEACHER(
  TEACHER_ID VARCHAR(10)  PRIMARY KEY,
  TEACHER_NAME VARCHAR(60),
  DEPT_ID VARCHAR(20),
  FOREIGN KEY(DEPT_ID)REFERENCES DEPARTMENT(DEPT_ID),
  SALARY INT,
  HIREDATE DATE
  );
  
  CREATE TABLE SUBJECTS(
  SUB_ID VARCHAR(10) PRIMARY KEY,
  SUB_NAME VARCHAR(50),
  DEPT_ID VARCHAR(10),
  TEACHER_ID VARCHAR(20),
  FOREIGN KEY(DEPT_ID)REFERENCES DEPARTMENT(DEPT_ID),
  FOREIGN KEY(TEACHER_ID)REFERENCES TEACHER(TEACHER_ID),
  CREDITS INT
  );
  
  CREATE TABLE STUDENT(
  STUD_ID VARCHAR(20) PRIMARY KEY,
  STUD_NAME VARCHAR(20),
  DEPT_ID VARCHAR(10),
  FOREIGN KEY(DEPT_ID)REFERENCES DEPARTMENT(DEPT_ID),
  GPA DECIMAL (3,2),
  ENR_YEAR INT
  );
  
  CREATE TABLE CLASSROOM(
  CLASS_ID VARCHAR(10) PRIMARY KEY,
  ROOM_NAME VARCHAR(20),
  SUB_ID VARCHAR(10),
  FOREIGN KEY(SUB_ID)REFERENCES SUBJECTS(SUB_ID),
  CAPACITY INT
  );
  
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_Name, Budget, Building) VALUES
('D1', 'Computer Science', 500000, 'Turing Hall'),
('D2', 'Mathematics', 250000, 'Gauss Tower'),
('D3', 'Physics', 300000, 'Einstein Lab'),
('D4', 'History', 120000, 'Lincoln Wing');


INSERT INTO Teacher (Teacher_ID, Teacher_Name, DepT_ID, Salary, HireDate) VALUES
('T101', 'Dr. Alan Turing', 'D1', 95000, '2018-03-12'),
('T102', 'Prof. Grace Hopper', 'D1', 88000, '2020-06-01'),
('T103', 'Dr. Carl Gauss', 'D2', 82000, '2015-09-15'),
('T104', 'Marie Curie', 'D3', 91000, '2019-01-20'),
('T105', 'Herodotus', 'D4', 60000, '2022-08-11');



INSERT INTO SUBJECTS (SUB_ID, SUB_Name, DEPT_ID, Teacher_ID, Credits) VALUES
('CS101', 'Introduction to Database', 'D1', 'T101', 4),
('CS102', 'Artificial Intelligence', 'D1', 'T102', 4),
('MA201', 'Linear Algebra', 'D2', 'T103', 3),
('PH301', 'Quantum Mechanics', 'D3', 'T104', 4),
('HI101', 'Ancient Civilizations', 'D4', 'T105', 2);

INSERT INTO Student (StuD_ID, Stud_Name, DepT_ID, GPA, Enr_Year)VALUES
('S1', 'Alice Smith', 'D1', 3.85, 2024),
('S2', 'Bob Jones', 'D1', 2.90, 2025),
('S3', 'Charlie Brown', 'D2', 3.40, 2024),
('S4', 'David Miller', 'D3', 3.92, 2023),
('S5', 'Eva Green', 'D4', 3.15, 2025);


INSERT INTO Classroom (Class_ID, Room_NAME, Sub_ID, Capacity)
VALUES
('C1', '101-A', 'CS101', 50),
('C2', '102-B', 'CS102', 35),
('C3', '201', 'MA201', 40),
('C4', 'Lab-3', 'PH301', 25),
('C5', '404', NULL, 60);
 
  
/* SELECT * FROM DEPARTMENT;
 SELECT * FROM TEACHER;
 SELECT * FROM SUBJECTS;
 SELECT * FROM STUDENT;
 SELECT * FROM CLASSROOM;
  
  SELECT C1.CLASS_ID,
  C1.ROOM_NAME,
  C1.SUB_NAME
  FROM
  CLASSROOM C1 RIGHT JOIN SUBJECT S1 
  ON S1.SUB_ID=C1.SUB_ID
  SELECT ENR_YEAR, 
  COUNT(*) AS NUMBER_OF_STUDENT 
  FROM Student GROUP BY ENR_YEAR 
  ORDER BY ENR_YEAR ASC;
  SELECT * FROM Student;
  ALTER TABLE Student MODIFY GPA DECIMAL;
  SELECT STUD_ID,
  STUD_NAME,
  GPA,
  ROW_NUMBER() OVER (ORDER BY GPA DESC) AS GPSRANK
  FROM Student;
  UPDATE Student SET GPA=33.40 WHERE STUD_ID='S5';
  SELECT STUD_ID,
  STUD_NAME,
  GPA,
  RANK() OVER (ORDER BY GPA DESC) AS GPSRANK
  FROM Student;
  SELECT STUD_ID,
  STUD_NAME,
  GPA,
  DENSE_RANK() OVER (ORDER BY GPA DESC) AS GPSRANK
  FROM Student;*/
  
  
  
  